sources:
- id: bloomberg_tech
  name: 彭博社(科技)
  url: https://feeds.bloomberg.com/technology/news.rss
  enabled: true
  language: en
  translate: true
- id: bloomberg_markets
  name: 彭博社(市场)
  url: https://feeds.bloomberg.com/markets/news.rss
  enabled: true
  language: en
  translate: true
- id: reuters_business
  name: 路透社(商业)
  url: http://feeds.reuters.com/reuters/businessNews
  enabled: true
  language: en
  translate: true
- id: caixin_macro
  name: 财新(宏观)
  url: https://www.caixin.com/rss/macro.xml
  enabled: true
  language: zh
  translate: false
- id: wallstreetcn_global
  name: 华尔街见闻(全球)
  url: https://api.wallstreetcn.com/v2/it/articles?channel=global&limit=20
  enabled: true
  language: zh
  translate: false
- id: simonwillison_net
  name: simonwillison.net
  url: https://simonwillison.net/atom/everything/
  enabled: true
  language: en
  translate: true
- id: jeffgeerling_com
  name: jeffgeerling.com
  url: https://www.jeffgeerling.com/blog.xml
  enabled: true
  language: en
  translate: true
- id: seangoedecke_com
  name: seangoedecke.com
  url: https://www.seangoedecke.com/rss.xml
  enabled: true
  language: en
  translate: true
- id: krebsonsecurity_com
  name: krebsonsecurity.com
  url: https://krebsonsecurity.com/feed/
  enabled: true
  language: en
  translate: true
- id: daringfireball_net
  name: daringfireball.net
  url: https://daringfireball.net/feeds/main
  enabled: true
  language: en
  translate: true
- id: ericmigi_com
  name: ericmigi.com
  url: https://ericmigi.com/rss.xml
  enabled: true
  language: en
  translate: true
- id: antirez_com
  name: antirez.com
  url: http://antirez.com/rss
  enabled: true
  language: en
  translate: true
- id: idiallo_com
  name: idiallo.com
  url: https://idiallo.com/feed.rss
  enabled: true
  language: en
  translate: true
- id: maurycyz_com
  name: maurycyz.com
  url: https://maurycyz.com/index.xml
  enabled: true
  language: en
  translate: true
- id: pluralistic_net
  name: pluralistic.net
  url: https://pluralistic.net/feed/
  enabled: true
  language: en
  translate: true
- id: shkspr_mobi
  name: shkspr.mobi
  url: https://shkspr.mobi/blog/feed/
  enabled: true
  language: en
  translate: true
- id: lcamtuf_substack_com
  name: lcamtuf.substack.com
  url: https://lcamtuf.substack.com/feed
  enabled: true
  language: en
  translate: true
- id: mitchellh_com
  name: mitchellh.com
  url: https://mitchellh.com/feed.xml
  enabled: true
  language: en
  translate: true
- id: dynomight_net
  name: dynomight.net
  url: https://dynomight.net/feed.xml
  enabled: true
  language: en
  translate: true
- id: utcc_utoronto_ca__cks
  name: utcc.utoronto.ca/~cks
  url: https://utcc.utoronto.ca/~cks/space/blog/?atom
  enabled: true
  language: en
  translate: true
- id: xeiaso_net
  name: xeiaso.net
  url: https://xeiaso.net/blog.rss
  enabled: true
  language: en
  translate: true
- id: devblogs_microsoft_com_oldnewthing
  name: devblogs.microsoft.com/oldnewthing
  url: https://devblogs.microsoft.com/oldnewthing/feed
  enabled: true
  language: en
  translate: true
- id: righto_com
  name: righto.com
  url: https://www.righto.com/feeds/posts/default
  enabled: true
  language: en
  translate: true
- id: lucumr_pocoo_org
  name: lucumr.pocoo.org
  url: https://lucumr.pocoo.org/feed.atom
  enabled: true
  language: en
  translate: true
- id: skyfall_dev
  name: skyfall.dev
  url: https://skyfall.dev/rss.xml
  enabled: true
  language: en
  translate: true
- id: garymarcus_substack_com
  name: garymarcus.substack.com
  url: https://garymarcus.substack.com/feed
  enabled: true
  language: en
  translate: true
- id: rachelbythebay_com
  name: rachelbythebay.com
  url: https://rachelbythebay.com/w/atom.xml
  enabled: true
  language: en
  translate: true
- id: overreacted_io
  name: overreacted.io
  url: https://overreacted.io/rss.xml
  enabled: true
  language: en
  translate: true
- id: timsh_org
  name: timsh.org
  url: https://timsh.org/rss/
  enabled: true
  language: en
  translate: true
- id: johndcook_com
  name: johndcook.com
  url: https://www.johndcook.com/blog/feed/
  enabled: true
  language: en
  translate: true
- id: gilesthomas_com
  name: gilesthomas.com
  url: https://gilesthomas.com/feed/rss.xml
  enabled: true
  language: en
  translate: true
- id: matklad_github_io
  name: matklad.github.io
  url: https://matklad.github.io/feed.xml
  enabled: true
  language: en
  translate: true
- id: derekthompson_org
  name: derekthompson.org
  url: https://www.theatlantic.com/feed/author/derek-thompson/
  enabled: true
  language: en
  translate: true
- id: evanhahn_com
  name: evanhahn.com
  url: https://evanhahn.com/feed.xml
  enabled: true
  language: en
  translate: true
- id: terriblesoftware_org
  name: terriblesoftware.org
  url: https://terriblesoftware.org/feed/
  enabled: true
  language: en
  translate: true
- id: rakhim_exotext_com
  name: rakhim.exotext.com
  url: https://rakhim.exotext.com/rss.xml
  enabled: true
  language: en
  translate: true
- id: joanwestenberg_com
  name: joanwestenberg.com
  url: https://joanwestenberg.com/rss
  enabled: true
  language: en
  translate: true
- id: xania_org
  name: xania.org
  url: https://xania.org/feed
  enabled: true
  language: en
  translate: true
- id: micahflee_com
  name: micahflee.com
  url: https://micahflee.com/feed/
  enabled: true
  language: en
  translate: true
- id: nesbitt_io
  name: nesbitt.io
  url: https://nesbitt.io/feed.xml
  enabled: true
  language: en
  translate: true
- id: construction_physics_com
  name: construction-physics.com
  url: https://www.construction-physics.com/feed
  enabled: true
  language: en
  translate: true
- id: tedium_co
  name: tedium.co
  url: https://feed.tedium.co/
  enabled: true
  language: en
  translate: true
- id: susam_net
  name: susam.net
  url: https://susam.net/feed.xml
  enabled: true
  language: en
  translate: true
- id: entropicthoughts_com
  name: entropicthoughts.com
  url: https://entropicthoughts.com/feed.xml
  enabled: true
  language: en
  translate: true
- id: buttondown_com_hillelwayne
  name: buttondown.com/hillelwayne
  url: https://buttondown.com/hillelwayne/rss
  enabled: true
  language: en
  translate: true
- id: dwarkesh_com
  name: dwarkesh.com
  url: https://www.dwarkeshpatel.com/feed
  enabled: true
  language: en
  translate: true
- id: borretti_me
  name: borretti.me
  url: https://borretti.me/feed.xml
  enabled: true
  language: en
  translate: true
- id: wheresyoured_at
  name: wheresyoured.at
  url: https://www.wheresyoured.at/rss/
  enabled: true
  language: en
  translate: true
- id: jayd_ml
  name: jayd.ml
  url: https://jayd.ml/feed.xml
  enabled: true
  language: en
  translate: true
- id: minimaxir_com
  name: minimaxir.com
  url: https://minimaxir.com/index.xml
  enabled: true
  language: en
  translate: true
- id: geohot_github_io
  name: geohot.github.io
  url: https://geohot.github.io/blog/feed.xml
  enabled: true
  language: en
  translate: true
- id: paulgraham_com
  name: paulgraham.com
  url: http://www.aaronsw.com/2002/feeds/pgessays.rss
  enabled: true
  language: en
  translate: true
- id: filfre_net
  name: filfre.net
  url: https://www.filfre.net/feed/
  enabled: true
  language: en
  translate: true
- id: blog_jim_nielsen_com
  name: blog.jim-nielsen.com
  url: https://blog.jim-nielsen.com/feed.xml
  enabled: true
  language: en
  translate: true
- id: dfarq_homeip_net
  name: dfarq.homeip.net
  url: https://dfarq.homeip.net/feed/
  enabled: true
  language: en
  translate: true
- id: jyn_dev
  name: jyn.dev
  url: https://jyn.dev/atom.xml
  enabled: true
  language: en
  translate: true
- id: geoffreylitt_com
  name: geoffreylitt.com
  url: https://www.geoffreylitt.com/feed.xml
  enabled: true
  language: en
  translate: true
- id: downtowndougbrown_com
  name: downtowndougbrown.com
  url: https://www.downtowndougbrown.com/feed/
  enabled: true
  language: en
  translate: true
- id: brutecat_com
  name: brutecat.com
  url: https://brutecat.com/rss.xml
  enabled: true
  language: en
  translate: true
- id: eli_thegreenplace_net
  name: eli.thegreenplace.net
  url: https://eli.thegreenplace.net/feeds/all.atom.xml
  enabled: true
  language: en
  translate: true
- id: abortretry_fail
  name: abortretry.fail
  url: https://www.abortretry.fail/feed
  enabled: true
  language: en
  translate: true
- id: fabiensanglard_net
  name: fabiensanglard.net
  url: https://fabiensanglard.net/rss.xml
  enabled: true
  language: en
  translate: true
- id: oldvcr_blogspot_com
  name: oldvcr.blogspot.com
  url: https://oldvcr.blogspot.com/feeds/posts/default
  enabled: true
  language: en
  translate: true
- id: bogdanthegeek_github_io
  name: bogdanthegeek.github.io
  url: https://bogdanthegeek.github.io/blog/index.xml
  enabled: true
  language: en
  translate: true
- id: hugotunius_se
  name: hugotunius.se
  url: https://hugotunius.se/feed.xml
  enabled: true
  language: en
  translate: true
- id: gwern_net
  name: gwern.net
  url: https://gwern.substack.com/feed
  enabled: true
  language: en
  translate: true
- id: berthub_eu
  name: berthub.eu
  url: https://berthub.eu/articles/index.xml
  enabled: true
  language: en
  translate: true
- id: chadnauseam_com
  name: chadnauseam.com
  url: https://chadnauseam.com/rss.xml
  enabled: true
  language: en
  translate: true
- id: simone_org
  name: simone.org
  url: https://simone.org/feed/
  enabled: true
  language: en
  translate: true
- id: it_notes_dragas_net
  name: it-notes.dragas.net
  url: https://it-notes.dragas.net/feed/
  enabled: true
  language: en
  translate: true
- id: beej_us
  name: beej.us
  url: https://beej.us/blog/rss.xml
  enabled: true
  language: en
  translate: true
- id: hey_paris
  name: hey.paris
  url: https://hey.paris/index.xml
  enabled: true
  language: en
  translate: true
- id: danielwirtz_com
  name: danielwirtz.com
  url: https://danielwirtz.com/rss.xml
  enabled: true
  language: en
  translate: true
- id: matduggan_com
  name: matduggan.com
  url: https://matduggan.com/rss/
  enabled: true
  language: en
  translate: true
- id: refactoringenglish_com
  name: refactoringenglish.com
  url: https://refactoringenglish.com/index.xml
  enabled: true
  language: en
  translate: true
- id: worksonmymachine_substack_com
  name: worksonmymachine.substack.com
  url: https://worksonmymachine.substack.com/feed
  enabled: true
  language: en
  translate: true
- id: philiplaine_com
  name: philiplaine.com
  url: https://philiplaine.com/index.xml
  enabled: true
  language: en
  translate: true
- id: steveblank_com
  name: steveblank.com
  url: https://steveblank.com/feed/
  enabled: true
  language: en
  translate: true
- id: bernsteinbear_com
  name: bernsteinbear.com
  url: https://bernsteinbear.com/feed.xml
  enabled: true
  language: en
  translate: true
- id: danieldelaney_net
  name: danieldelaney.net
  url: https://danieldelaney.net/feed
  enabled: true
  language: en
  translate: true
- id: troyhunt_com
  name: troyhunt.com
  url: https://www.troyhunt.com/rss/
  enabled: true
  language: en
  translate: true
- id: herman_bearblog_dev
  name: herman.bearblog.dev
  url: https://herman.bearblog.dev/feed/
  enabled: true
  language: en
  translate: true
- id: tomrenner_com
  name: tomrenner.com
  url: https://tomrenner.com/index.xml
  enabled: true
  language: en
  translate: true
- id: blog_pixelmelt_dev
  name: blog.pixelmelt.dev
  url: https://blog.pixelmelt.dev/rss/
  enabled: true
  language: en
  translate: true
- id: martinalderson_com
  name: martinalderson.com
  url: https://martinalderson.com/feed.xml
  enabled: true
  language: en
  translate: true
- id: danielchasehooper_com
  name: danielchasehooper.com
  url: https://danielchasehooper.com/feed.xml
  enabled: true
  language: en
  translate: true
- id: chiark_greenend_org_uk__sgtatham
  name: chiark.greenend.org.uk/~sgtatham
  url: https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/feed.xml
  enabled: true
  language: en
  translate: true
- id: grantslatton_com
  name: grantslatton.com
  url: https://grantslatton.com/rss.xml
  enabled: true
  language: en
  translate: true
- id: experimental_history_com
  name: experimental-history.com
  url: https://www.experimental-history.com/feed
  enabled: true
  language: en
  translate: true
- id: anildash_com
  name: anildash.com
  url: https://anildash.com/feed.xml
  enabled: true
  language: en
  translate: true
- id: aresluna_org
  name: aresluna.org
  url: https://aresluna.org/main.rss
  enabled: true
  language: en
  translate: true
- id: michael_stapelberg_ch
  name: michael.stapelberg.ch
  url: https://michael.stapelberg.ch/feed.xml
  enabled: true
  language: en
  translate: true
- id: miguelgrinberg_com
  name: miguelgrinberg.com
  url: https://blog.miguelgrinberg.com/feed
  enabled: true
  language: en
  translate: true
- id: keygen_sh
  name: keygen.sh
  url: https://keygen.sh/blog/feed.xml
  enabled: true
  language: en
  translate: true
- id: mjg59_dreamwidth_org
  name: mjg59.dreamwidth.org
  url: https://mjg59.dreamwidth.org/data/rss
  enabled: true
  language: en
  translate: true
- id: computer_rip
  name: computer.rip
  url: https://computer.rip/rss.xml
  enabled: true
  language: en
  translate: true
- id: tedunangst_com
  name: tedunangst.com
  url: https://www.tedunangst.com/flak/rss
  enabled: true
  language: en
  translate: true
